<?php
/**
 * Optimized copies of local stylesheets and scripts.
 *
 * Originals are never modified. A copy lives in the public cache directory
 * under a deterministic name:
 *
 *   <source-slug>-<basename>-<hash>.min.(css|js)
 *   hash = md5( realpath | filemtime | filesize | plugin version | sorted transform ids ), 10 chars
 *
 * so a changed original or a different set of transforms automatically yields a
 * new file. When a copy would bring no benefit or cannot be produced safely, an
 * empty "<name>.skip.txt" marker remembers that decision (until the original or
 * the transform set changes).
 *
 * Frontend requests only generate small files synchronously (≤ 100 KB, at most
 * two per request, 50 ms budget); everything else is queued (option
 * `shso_asset_queue`, max 500 entries) and generated by the cron hook
 * `shso_generate_assets`. Copies that no rendered page referenced for 45 days are
 * garbage collected (used copies are touched at most once a week).
 *
 * @package SH\SpeedOptimizer
 */

namespace SH\SpeedOptimizer\Assets;

use SH\SpeedOptimizer\Assets\Minify\CssMinifier;
use SH\SpeedOptimizer\Assets\Minify\JsMinifier;
use SH\SpeedOptimizer\Core\Filesystem;
use SH\SpeedOptimizer\Core\Plugin;
use SH\SpeedOptimizer\Core\Scheduler;
use SH\SpeedOptimizer\Diagnostics\Logger;

defined( 'ABSPATH' ) || exit;

/**
 * Asset copy generator.
 */
final class AssetCopies {

	public const CRON_HOOK    = 'shso_generate_assets';
	public const QUEUE_OPTION = 'shso_asset_queue';
	public const QUEUE_MAX    = 500;
	public const SUBDIR       = 'assets';

	public const MINIFY_CSS = 'css_minify';
	public const MINIFY_JS  = 'js_minify';

	/**
	 * Default limits.
	 */
	private const DEFAULT_LIMITS = array(
		'sync_max_bytes' => 102400,
		'sync_max_count' => 2,
		'sync_budget_ms' => 50.0,
		'batch'          => 20,
		'batch_seconds'  => 20.0,
		'max_age'        => 3888000, // 45 days without being referenced.
		'touch_after'    => 604800,  // Refresh the "last used" time at most weekly.
	);

	/**
	 * Minimum output/input size ratio; anything smaller is treated as a broken result.
	 */
	private const MIN_RATIO = array(
		'css' => 0.2,
		'js'  => 0.3,
	);

	/**
	 * Patterns of scripts that compute URLs from their own location (a copy in another
	 * directory would load chunks/files from the wrong place).
	 */
	private const LOCATION_SENSITIVE = array( 'currentScript', 'webpackChunk', 'webpackJsonp', '__webpack_public_path__', 'import.meta', 'getElementsByTagName("script")', "getElementsByTagName('script')", 'document.scripts' );

	/**
	 * Request singleton.
	 *
	 * @var AssetCopies|null
	 */
	private static ?AssetCopies $instance = null;

	/**
	 * Filesystem.
	 *
	 * @var Filesystem
	 */
	private Filesystem $fs;

	/**
	 * Provider of content transforms: function( string $type ): array<string,callable>.
	 *
	 * @var callable|null
	 */
	private $transforms;

	/**
	 * Logger.
	 *
	 * @var Logger|null
	 */
	private ?Logger $logger;

	/**
	 * Limits.
	 *
	 * @var array<string,int|float>
	 */
	private array $limits;

	/**
	 * Synchronous generations in this request.
	 *
	 * @var int
	 */
	private int $sync_count = 0;

	/**
	 * Milliseconds spent on synchronous generation in this request.
	 *
	 * @var float
	 */
	private float $sync_ms = 0.0;

	/**
	 * Queue entries to persist at the end of the request.
	 *
	 * @var array<string,array<string,mixed>>
	 */
	private array $pending = array();

	/**
	 * Constructor.
	 *
	 * @param Filesystem          $fs         Filesystem.
	 * @param callable|null       $transforms function( string $type ): array<string,callable> in priority order.
	 * @param Logger|null         $logger     Logger.
	 * @param array<string,mixed> $limits     Limit overrides (see DEFAULT_LIMITS).
	 */
	public function __construct( Filesystem $fs, ?callable $transforms = null, ?Logger $logger = null, array $limits = array() ) {
		$this->fs         = $fs;
		$this->transforms = $transforms;
		$this->logger     = $logger;
		$this->limits     = array_merge( self::DEFAULT_LIMITS, $limits );
	}

	/**
	 * Request singleton wired to the plugin container.
	 */
	public static function instance(): self {
		if ( null === self::$instance ) {
			$plugin         = Plugin::instance();
			$runtime        = $plugin->runtime();
			self::$instance = new self(
				$plugin->filesystem(),
				static function ( string $type ) use ( $runtime ): array {
					return 'css' === $type ? $runtime->css_transforms() : $runtime->js_transforms();
				},
				$plugin->logger()
			);
		}
		return self::$instance;
	}

	/**
	 * Replace the singleton (tests) or drop it.
	 *
	 * @param AssetCopies|null $instance Instance.
	 */
	public static function set_instance( ?AssetCopies $instance ): void {
		self::$instance = $instance;
	}

	/**
	 * Generate (or find) the optimized copy of a local asset right now. Used by the engine to
	 * pre-generate copies for scanned pages before verification.
	 *
	 * @param string        $url           Asset URL.
	 * @param string        $type          css|js.
	 * @param string[]|null $transform_ids Transform ids; default: minify + every registered transform.
	 * @return string|null Copy URL, or null when no copy exists (not local, excluded, no benefit, failed).
	 */
	public static function generate( string $url, string $type, ?array $transform_ids = null ): ?string {
		if ( ! in_array( $type, array( 'css', 'js' ), true ) ) {
			return null;
		}
		$copies = self::instance();
		$ids    = $transform_ids ?? $copies->default_ids( $type );
		return $copies->copy_url( $url, $type, $ids, 'force' );
	}

	/**
	 * Adjust limits (e.g. larger synchronous budget for signed verification requests).
	 *
	 * @param array<string,mixed> $limits Limits.
	 */
	public function set_limits( array $limits ): void {
		$this->limits = array_merge( $this->limits, $limits );
	}

	/**
	 * Default transform ids for a type: minify plus all registered transforms.
	 *
	 * @param string $type css|js.
	 * @return string[]
	 */
	public function default_ids( string $type ): array {
		$ids = array_keys( $this->transforms_for( $type ) );
		array_unshift( $ids, 'css' === $type ? self::MINIFY_CSS : self::MINIFY_JS );
		return self::normalize_ids( $ids );
	}

	/**
	 * URL of the optimized copy of an asset, generating it when allowed.
	 *
	 * @param string   $url  Asset URL as found in the page.
	 * @param string   $type css|js.
	 * @param string[] $ids  Transform ids active for this page.
	 * @param string   $mode frontend (budgeted synchronous generation, else queue) | force (generate now) | lookup (never generate).
	 * @return string|null Copy URL or null (serve the original).
	 */
	public function copy_url( string $url, string $type, array $ids, string $mode = 'frontend' ): ?string {
		$ids = self::normalize_ids( $ids );
		if ( empty( $ids ) ) {
			return null;
		}

		$source = AssetSource::resolve( $url, 'force' === $mode );
		if ( null === $source || $source['ext'] !== $type || AssetSource::TYPE_GENERATED === $source['source_type'] ) {
			return null;
		}

		$name = self::copy_name( $source, $type, $ids );
		$path = $this->dir() . $name;

		if ( is_file( $path ) ) {
			$this->touch( $path );
			return $this->public_url( $name, $url );
		}
		if ( is_file( $path . '.skip.txt' ) ) {
			$this->touch( $path . '.skip.txt' );
			return null;
		}
		if ( 'lookup' === $mode ) {
			return null;
		}

		if ( 'force' === $mode || $this->may_generate_now( (int) $source['bytes'] ) ) {
			$started = microtime( true );
			$result  = $this->build( $source, $type, $ids );
			if ( 'force' !== $mode ) {
				++$this->sync_count;
				$this->sync_ms += ( microtime( true ) - $started ) * 1000;
			}
			return 'ok' === $result['status'] ? $this->public_url( $name, $url ) : null;
		}

		$this->enqueue( $url, $type, $ids, $name );
		return null;
	}

	/**
	 * Generate a copy (or a skip marker) for a resolved source.
	 *
	 * @param array<string,mixed> $source Resolved source (AssetSource::resolve()).
	 * @param string              $type   css|js.
	 * @param string[]            $ids    Transform ids.
	 * @return array{status:string,reason:string,path:string} status: ok|skipped|failed.
	 */
	public function build( array $source, string $type, array $ids ): array {
		$ids  = self::normalize_ids( $ids );
		$name = self::copy_name( $source, $type, $ids );
		$path = $this->dir( true ) . $name;

		$contents = @file_get_contents( (string) $source['path'] ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged,WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Validated local file.
		if ( false === $contents ) {
			return $this->mark( $path, 'failed', 'unreadable' );
		}

		$transforms = $this->transforms_for( $type );
		try {
			$result = self::process( $contents, (string) $source['url'], $type, $ids, $transforms, $this->root_relative( (string) $source['url'] ) );
		} catch ( \Throwable $e ) {
			$result = array(
				'status' => 'failed',
				'output' => '',
				'reason' => 'exception: ' . $e->getMessage(),
			);
		}

		if ( 'ok' !== $result['status'] ) {
			return $this->mark( $path, $result['status'], $result['reason'] );
		}

		if ( ! $this->fs->write( $path, $result['output'] ) ) {
			$this->log( 'Could not write optimized asset copy.', array( 'file' => $name ) );
			return array(
				'status' => 'failed',
				'reason' => 'write_failed',
				'path'   => $path,
			);
		}

		/**
		 * Fires after an optimized asset copy was written.
		 *
		 * @param string              $path   Copy path.
		 * @param array<string,mixed> $source Resolved source.
		 * @param string[]            $ids    Transform ids applied.
		 */
		do_action( 'shso_asset_copy_generated', $path, $source, $ids );

		return array(
			'status' => 'ok',
			'reason' => '',
			'path'   => $path,
		);
	}

	/**
	 * The generation pipeline (pure).
	 *
	 * CSS: rewrite relative url()/@import references → content transforms → minify.
	 * JS: content transforms → minify. Source map references are removed. The result is
	 * rejected when empty or suspiciously small.
	 *
	 * @param string                 $contents      Original contents.
	 * @param string                 $url           Absolute URL of the original.
	 * @param string                 $type          css|js.
	 * @param string[]               $ids           Transform ids.
	 * @param array<string,callable> $transforms    Registered transforms (id => callable) in priority order.
	 * @param bool                   $root_relative Rewrite CSS references as root-relative paths.
	 * @return array{status:string,output:string,reason:string} status: ok|skipped|failed.
	 */
	public static function process( string $contents, string $url, string $type, array $ids, array $transforms, bool $root_relative = false ): array {
		$fail = static function ( string $status, string $reason ): array {
			return array(
				'status' => $status,
				'output' => '',
				'reason' => $reason,
			);
		};

		if ( '' === trim( $contents ) ) {
			return $fail( 'skipped', 'empty' );
		}

		$minify_id = 'css' === $type ? self::MINIFY_CSS : self::MINIFY_JS;
		$minify    = in_array( $minify_id, $ids, true );
		$already   = 'css' === $type ? CssMinifier::is_minified( $contents ) : JsMinifier::is_minified( $contents );
		$others    = array_values( array_diff( $ids, array( $minify_id ) ) );

		if ( empty( $others ) && ( ! $minify || $already ) ) {
			return $fail( 'skipped', 'already_minified' );
		}

		if ( 'js' === $type ) {
			foreach ( self::LOCATION_SENSITIVE as $needle ) {
				if ( false !== strpos( $contents, $needle ) ) {
					return $fail( 'skipped', 'location_sensitive' );
				}
			}
		}

		$output = $contents;
		if ( 'css' === $type ) {
			$output = CssMinifier::rewrite_urls( $output, $url, $root_relative );
			if ( null === $output ) {
				return $fail( 'skipped', 'unparsable' );
			}
		}

		foreach ( $others as $id ) {
			if ( ! isset( $transforms[ $id ] ) || ! is_callable( $transforms[ $id ] ) ) {
				return $fail( 'failed', 'transform_unavailable:' . $id );
			}
		}
		foreach ( $transforms as $id => $transform ) {
			if ( ! in_array( $id, $others, true ) ) {
				continue;
			}
			$transformed = $transform( $output, $url );
			if ( ! is_string( $transformed ) ) {
				return $fail( 'failed', 'transform_failed:' . $id );
			}
			$output = $transformed;
		}

		if ( $minify && ! $already ) {
			$output = 'css' === $type ? CssMinifier::minify( $output ) : JsMinifier::minify( $output );
		}

		$output = self::strip_source_map( $output, $type );

		if ( '' === trim( $output ) ) {
			return $fail( 'failed', 'empty_output' );
		}
		if ( strlen( $output ) < strlen( $contents ) * self::MIN_RATIO[ $type ] ) {
			return $fail( 'failed', 'suspicious_size' );
		}
		if ( empty( $others ) && strlen( $output ) > strlen( $contents ) * 0.99 ) {
			return $fail( 'skipped', 'no_benefit' );
		}

		return array(
			'status' => 'ok',
			'output' => $output,
			'reason' => '',
		);
	}

	/**
	 * Remove a trailing source map reference (the map would resolve against the copy's location).
	 *
	 * @param string $code Code.
	 * @param string $type css|js.
	 */
	public static function strip_source_map( string $code, string $type ): string {
		if ( false === strpos( $code, 'sourceMappingURL' ) ) {
			return $code;
		}
		if ( 'css' === $type ) {
			$stripped = preg_replace( '~\s*/\*[#@]\s*sourceMappingURL=[^*]*\*/\s*$~', "\n", $code );
		} else {
			$stripped = preg_replace( '~(^|\n)[ \t]*//[#@][ \t]*sourceMappingURL=[^\s\'"]*[ \t]*\s*$~', "\n", $code );
		}
		return is_string( $stripped ) ? $stripped : $code;
	}

	/**
	 * Deterministic copy file name.
	 *
	 * @param array<string,mixed> $source Resolved source.
	 * @param string              $type   css|js.
	 * @param string[]            $ids    Transform ids.
	 */
	public static function copy_name( array $source, string $type, array $ids ): string {
		$slug = self::sanitize_part( (string) ( $source['source_slug'] ?? 'asset' ), 40 );
		$base = (string) preg_replace( '/(\.min)?\.(css|js)$/i', '', basename( (string) $source['path'] ) );
		$base = self::sanitize_part( $base, 40 );
		return $slug . '-' . $base . '-' . self::hash( $source, $ids ) . '.min.' . ( 'css' === $type ? 'css' : 'js' );
	}

	/**
	 * Content/version hash of a copy.
	 *
	 * @param array<string,mixed> $source Resolved source.
	 * @param string[]            $ids    Transform ids.
	 */
	public static function hash( array $source, array $ids ): string {
		$ids     = self::normalize_ids( $ids );
		$version = defined( 'SHSO_VERSION' ) ? (string) SHSO_VERSION : '0';
		return substr( md5( $source['path'] . '|' . (int) $source['mtime'] . '|' . (int) $source['bytes'] . '|' . $version . '|' . implode( ',', $ids ) ), 0, 10 );
	}

	/**
	 * Queue an asset for background generation.
	 *
	 * @param string      $url  Asset URL.
	 * @param string      $type css|js.
	 * @param string[]    $ids  Transform ids.
	 * @param string|null $key  Queue key (copy name).
	 */
	public function enqueue( string $url, string $type, array $ids, ?string $key = null ): void {
		$key = $key ?? md5( $type . '|' . $url . '|' . implode( ',', self::normalize_ids( $ids ) ) );
		if ( isset( $this->pending[ $key ] ) || count( $this->pending ) >= 100 ) {
			return;
		}
		$this->pending[ $key ] = array(
			'url'  => $url,
			'type' => $type,
			'ids'  => self::normalize_ids( $ids ),
			'at'   => time(),
		);
	}

	/**
	 * Persist queued entries (one option write per request at most) and schedule the worker.
	 */
	public function flush_queue(): void {
		if ( empty( $this->pending ) ) {
			return;
		}
		$pending       = $this->pending;
		$this->pending = array();

		$queue   = self::read_queue();
		$changed = false;
		foreach ( $pending as $key => $entry ) {
			if ( isset( $queue[ $key ] ) ) {
				continue;
			}
			if ( count( $queue ) >= self::QUEUE_MAX ) {
				break;
			}
			$queue[ $key ] = $entry;
			$changed       = true;
		}

		if ( $changed ) {
			update_option( self::QUEUE_OPTION, $queue, false );
			Scheduler::async( self::CRON_HOOK, array(), 5 );
		}
	}

	/**
	 * Number of queued entries (including those not yet persisted).
	 */
	public function queue_size(): int {
		return count( self::read_queue() ) + count( $this->pending );
	}

	/**
	 * Remove queued entries (all, or of one type).
	 *
	 * @param string|null $type css|js or null for all.
	 */
	public function clear_queue( ?string $type = null ): void {
		if ( null === $type ) {
			delete_option( self::QUEUE_OPTION );
			return;
		}
		$queue = array_filter(
			self::read_queue(),
			static function ( $entry ) use ( $type ) {
				return ( $entry['type'] ?? '' ) !== $type;
			}
		);
		update_option( self::QUEUE_OPTION, $queue, false );
	}

	/**
	 * Cron worker: generate a batch of queued copies.
	 *
	 * @return int Number of processed entries.
	 */
	public function run_queue(): int {
		$queue = self::read_queue();
		if ( empty( $queue ) ) {
			return 0;
		}

		$started   = microtime( true );
		$processed = array();

		foreach ( $queue as $key => $entry ) {
			if ( count( $processed ) >= (int) $this->limits['batch'] || microtime( true ) - $started > (float) $this->limits['batch_seconds'] ) {
				break;
			}
			$processed[] = $key;
			try {
				$this->generate_entry( (array) $entry );
			} catch ( \Throwable $e ) {
				$this->log( 'Asset copy generation failed.', array( 'error' => $e->getMessage() ) );
			}
		}

		// Re-read: frontend requests may have added entries meanwhile.
		$current = self::read_queue();
		foreach ( $processed as $key ) {
			unset( $current[ $key ] );
		}
		update_option( self::QUEUE_OPTION, $current, false );

		if ( ! empty( $current ) ) {
			Scheduler::async( self::CRON_HOOK, array(), 30 );
		}

		return count( $processed );
	}

	/**
	 * Delete copies and markers no page referenced for a long time, and stale temp files.
	 *
	 * @param int|null $now Current time (tests).
	 * @return int Number of deleted files.
	 */
	public function garbage_collect( ?int $now = null ): int {
		$now = $now ?? time();
		$dir = $this->dir();
		if ( ! is_dir( $dir ) ) {
			return 0;
		}
		$items = @scandir( $dir ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		if ( false === $items ) {
			return 0;
		}

		$deleted = 0;
		foreach ( array_slice( $items, 0, 20000 ) as $item ) {
			$path = $dir . $item;
			if ( ! is_file( $path ) ) {
				continue;
			}
			$mtime = (int) @filemtime( $path ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
			if ( preg_match( '/\.min\.(css|js)(\.skip\.txt)?$/', $item ) ) {
				if ( $mtime < $now - (int) $this->limits['max_age'] && $this->fs->delete( $path ) ) {
					++$deleted;
				}
			} elseif ( '.tmp' === substr( $item, -4 ) && $mtime < $now - DAY_IN_SECONDS && $this->fs->delete( $path ) ) {
				++$deleted;
			}
		}
		return $deleted;
	}

	/**
	 * Counts for the dashboard: copies per type, skip markers, queued entries.
	 *
	 * @return array{css:int,js:int,skipped:int,queued:int,bytes:int}
	 */
	public function stats(): array {
		$stats = array(
			'css'     => 0,
			'js'      => 0,
			'skipped' => 0,
			'queued'  => $this->queue_size(),
			'bytes'   => 0,
		);
		$dir   = $this->dir();
		$items = is_dir( $dir ) ? @scandir( $dir ) : false; // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		foreach ( is_array( $items ) ? array_slice( $items, 0, 20000 ) : array() as $item ) {
			if ( preg_match( '/\.min\.(css|js)$/', $item, $m ) ) {
				++$stats[ $m[1] ];
				$stats['bytes'] += (int) @filesize( $dir . $item ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
			} elseif ( '.skip.txt' === substr( $item, -9 ) ) {
				++$stats['skipped'];
			}
		}
		return $stats;
	}

	/**
	 * Directory of the copies (with trailing slash).
	 *
	 * @param bool $create Create (and protect) it when missing.
	 */
	public function dir( bool $create = false ): string {
		return $create ? $this->fs->cache_dir( self::SUBDIR, true ) : Filesystem::cache_root() . self::SUBDIR . '/';
	}

	/**
	 * Public URL of a copy, keeping the form of the original reference
	 * (absolute, protocol-relative or root-relative) when both are on the same host.
	 *
	 * @param string $name         Copy file name.
	 * @param string $original_url Original reference.
	 */
	public function public_url( string $name, string $original_url ): string {
		$copy  = Filesystem::cache_url() . self::SUBDIR . '/' . $name;
		$parts = wp_parse_url( $copy );
		if ( ! is_array( $parts ) || empty( $parts['host'] ) ) {
			return $copy;
		}
		$path     = $parts['path'] ?? '';
		$original = trim( $original_url );
		$host     = strtolower( $parts['host'] ) . ( isset( $parts['port'] ) ? ':' . $parts['port'] : '' );

		if ( 0 === strpos( $original, '//' ) ) {
			$orig_host = (string) wp_parse_url( 'http:' . $original, PHP_URL_HOST );
			$orig_port = wp_parse_url( 'http:' . $original, PHP_URL_PORT );
			return strtolower( $orig_host ) . ( $orig_port ? ':' . $orig_port : '' ) === $host ? '//' . $host . $path : $copy;
		}
		if ( '' !== $original && '/' === $original[0] ) {
			return $path;
		}
		$orig = wp_parse_url( $original );
		if ( is_array( $orig ) && ! empty( $orig['host'] ) && strtolower( $orig['host'] ) . ( isset( $orig['port'] ) ? ':' . $orig['port'] : '' ) === $host ) {
			return ( $orig['scheme'] ?? 'https' ) . '://' . $host . $path;
		}
		return $copy;
	}

	/**
	 * Whether synchronous generation fits into this request's budget.
	 *
	 * @param int $bytes Source size.
	 */
	private function may_generate_now( int $bytes ): bool {
		return $bytes <= (int) $this->limits['sync_max_bytes']
			&& $this->sync_count < (int) $this->limits['sync_max_count']
			&& $this->sync_ms < (float) $this->limits['sync_budget_ms'];
	}

	/**
	 * Generate one queued entry.
	 *
	 * @param array<string,mixed> $entry Queue entry.
	 */
	private function generate_entry( array $entry ): void {
		$type = (string) ( $entry['type'] ?? '' );
		if ( ! in_array( $type, array( 'css', 'js' ), true ) ) {
			return;
		}
		$ids    = self::normalize_ids( (array) ( $entry['ids'] ?? array() ) );
		$source = AssetSource::resolve( (string) ( $entry['url'] ?? '' ) );
		if ( null === $source || $source['ext'] !== $type || AssetSource::TYPE_GENERATED === $source['source_type'] ) {
			return;
		}
		$available = array_keys( $this->transforms_for( $type ) );
		foreach ( $ids as $id ) {
			if ( self::MINIFY_CSS !== $id && self::MINIFY_JS !== $id && ! in_array( $id, $available, true ) ) {
				$this->log( 'Queued asset skipped: transform not available in the background.', array( 'transform' => $id ) );
				return;
			}
		}
		$path = $this->dir() . self::copy_name( $source, $type, $ids );
		if ( is_file( $path ) || is_file( $path . '.skip.txt' ) ) {
			return;
		}
		$this->build( $source, $type, $ids );
	}

	/**
	 * Write a skip marker and return the result.
	 *
	 * @param string $path   Copy path.
	 * @param string $status skipped|failed.
	 * @param string $reason Reason.
	 * @return array{status:string,reason:string,path:string}
	 */
	private function mark( string $path, string $status, string $reason ): array {
		$this->fs->write( $path . '.skip.txt', $status . ': ' . $reason );
		if ( 'failed' === $status ) {
			$this->log( 'Optimized asset copy discarded; the original stays in use.', array( 'file' => basename( $path ), 'reason' => $reason ) );
		}
		return array(
			'status' => $status,
			'reason' => $reason,
			'path'   => $path,
		);
	}

	/**
	 * Refresh a file's modification time (its "last used" time) at most weekly.
	 *
	 * @param string $path File path.
	 */
	private function touch( string $path ): void {
		$mtime = (int) @filemtime( $path ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		if ( $mtime > 0 && $mtime < time() - (int) $this->limits['touch_after'] && $this->fs->is_allowed_path( $path ) ) {
			@touch( $path ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		}
	}

	/**
	 * Registered transforms for a type.
	 *
	 * @param string $type css|js.
	 * @return array<string,callable>
	 */
	private function transforms_for( string $type ): array {
		if ( null === $this->transforms ) {
			return array();
		}
		$list = ( $this->transforms )( $type );
		return is_array( $list ) ? $list : array();
	}

	/**
	 * Whether CSS references in a copy of this URL can be root-relative (same host as the cache).
	 *
	 * @param string $url Original URL.
	 */
	private function root_relative( string $url ): bool {
		$source_host = strtolower( (string) wp_parse_url( $url, PHP_URL_HOST ) );
		$cache_host  = strtolower( (string) wp_parse_url( Filesystem::cache_url(), PHP_URL_HOST ) );
		return '' !== $source_host && $source_host === $cache_host
			&& wp_parse_url( $url, PHP_URL_PORT ) === wp_parse_url( Filesystem::cache_url(), PHP_URL_PORT );
	}

	/**
	 * Stored queue.
	 *
	 * @return array<string,array<string,mixed>>
	 */
	private static function read_queue(): array {
		$queue = get_option( self::QUEUE_OPTION, array() );
		return is_array( $queue ) ? $queue : array();
	}

	/**
	 * Sorted, unique, sanitized ids.
	 *
	 * @param string[] $ids Ids.
	 * @return string[]
	 */
	private static function normalize_ids( array $ids ): array {
		$ids = array_values( array_unique( array_filter( array_map( 'sanitize_key', array_map( 'strval', $ids ) ) ) ) );
		sort( $ids );
		return $ids;
	}

	/**
	 * File name part: lower-case letters, digits and dashes.
	 *
	 * @param string $value Raw.
	 * @param int    $max   Maximum length.
	 */
	private static function sanitize_part( string $value, int $max ): string {
		$value = trim( (string) preg_replace( '/[^a-z0-9]+/', '-', strtolower( $value ) ), '-' );
		$value = substr( $value, 0, $max );
		return '' === $value ? 'asset' : rtrim( $value, '-' );
	}

	/**
	 * Debug log.
	 *
	 * @param string              $message Message.
	 * @param array<string,mixed> $context Context.
	 */
	private function log( string $message, array $context = array() ): void {
		if ( null !== $this->logger ) {
			$this->logger->debug( $message, $context, 'assets' );
		}
	}
}
