<?php
/**
 * Font display swap: text stays visible while web fonts load.
 *
 * @package SH\SpeedOptimizer
 */

namespace SH\SpeedOptimizer\Modules\FontOptimization;

use SH\SpeedOptimizer\Assets\Fonts\FontFaceTransformer;
use SH\SpeedOptimizer\Assets\Fonts\GoogleFonts;
use SH\SpeedOptimizer\Assets\HtmlDocument;
use SH\SpeedOptimizer\Assets\Tag;
use SH\SpeedOptimizer\Optimization\AbstractOptimization;
use SH\SpeedOptimizer\Optimization\Assessment;
use SH\SpeedOptimizer\Optimization\AssessmentContext;
use SH\SpeedOptimizer\Optimization\Category;
use SH\SpeedOptimizer\Optimization\Risk;
use SH\SpeedOptimizer\Optimization\Runtime;

defined( 'ABSPATH' ) || exit;

/**
 * Font display swap.
 */
final class FontDisplayOptimization extends AbstractOptimization {

	/**
	 * {@inheritDoc}
	 */
	public function id(): string {
		return 'font_display_swap';
	}

	/**
	 * {@inheritDoc}
	 */
	public function name(): string {
		return __( 'Show text while fonts load', 'sh-speed-optimizer' );
	}

	/**
	 * {@inheritDoc}
	 */
	public function description(): string {
		return __( 'Visitors can read your text right away in a standard font; your custom font replaces it as soon as it has loaded. Icon fonts are never changed.', 'sh-speed-optimizer' );
	}

	/**
	 * {@inheritDoc}
	 */
	public function category(): string {
		return Category::FONTS;
	}

	/**
	 * {@inheritDoc}
	 */
	public function risk(): string {
		return Risk::SAFE;
	}

	/**
	 * {@inheritDoc}
	 */
	public function level(): string {
		return Risk::LEVEL_SAFE;
	}

	/**
	 * {@inheritDoc}
	 *
	 * @param AssessmentContext $context Scan data.
	 */
	public function assess( AssessmentContext $context ): Assessment {
		$missing = $context->sum( 'fonts.font_display_missing' );
		$google  = 0;
		foreach ( $context->pages() as $page ) {
			foreach ( (array) ( $page['fonts']['google'] ?? array() ) as $font ) {
				$url = is_array( $font ) ? (string) ( $font['url'] ?? '' ) : '';
				if ( '' !== $url && empty( $font['display'] ) && GoogleFonts::add_display_swap( $url ) !== $url ) {
					++$google;
				}
			}
		}

		if ( 0 === $missing && 0 === $google ) {
			return $this->finalize(
				Assessment::not_applicable( __( 'Your fonts already keep text visible while loading, or no web fonts were found.', 'sh-speed-optimizer' ) ),
				$context,
				'font_optimization'
			);
		}

		$assessment       = Assessment::make( true, 95, Assessment::BENEFIT_MEDIUM );
		$assessment->data = array(
			'font_faces_without_display' => $missing,
			'google_fonts_without_swap'  => $google,
		);
		$assessment->note( __( 'Some fonts hide your text until they have finished loading.', 'sh-speed-optimizer' ) );

		return $this->finalize( $assessment, $context, 'font_optimization' );
	}

	/**
	 * {@inheritDoc}
	 *
	 * @param Runtime $runtime Runtime.
	 */
	public function register_runtime( Runtime $runtime ): void {
		// Optimized stylesheet copies generated by the asset pipeline.
		$runtime->add_css_transform(
			$this->id(),
			static function ( string $css, string $source_url = '' ): string {
				unset( $source_url );
				return FontFaceTransformer::process( $css );
			},
			30
		);

		$runtime->add_html_transform(
			$this->id(),
			static function ( HtmlDocument $doc ) {
				self::transform( $doc );
			},
			30
		);
	}

	/**
	 * Transform a document: Google Fonts links, inline @font-face rules and @imports.
	 *
	 * @param HtmlDocument $doc Document.
	 * @return int Changes.
	 */
	public static function transform( HtmlDocument $doc ): int {
		$changed = 0;

		if ( $doc->contains( 'fonts.googleapis.com' ) ) {
			$changed += $doc->replace_tags(
				'link',
				static function ( Tag $tag ) {
					$href = $tag->get( 'href' );
					if ( 'link' !== $tag->name || null === $href || ! GoogleFonts::is_css_url( $href ) ) {
						return null;
					}
					$new = GoogleFonts::add_display_swap( $href );
					return $new === $href ? null : $tag->set( 'href', $new );
				}
			);
		}

		if ( $doc->contains( '@font-face' ) || $doc->contains( '@import' ) ) {
			$changed += $doc->replace_styles(
				static function ( Tag $tag, string $css ) {
					$new = FontFaceTransformer::process( $css );
					return $new === $css ? null : $tag->to_html() . $new . '</style>';
				}
			);
		}

		return $changed;
	}
}
